stages:
  - test

UnitTest:
  image: python:3.8.10
  stage: test
  before_script:
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
    - echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list
    - pip install -r requirements.txt
  script:
    - coverage run manage.py test apps
    - coverage report -m
    - coverage xml -i
    - coverage-badge -o coverage.svg