stages:
  - test

UnitTest:
  image: python:3.8.10
  stage: test
  services:
    - postgres:14
  variables:
    POSTGRES_DB: tests
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
  cache:
    paths:
      - ~/.cache/pip/
  before_script:
    - export DATABASE_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB
    - pip install -r requirements.txt
  script:
    - coverage run manage.py test apps