stages:
  - test
  - sonarqube

UnitTest:
  image: python:3.8.10
  stage: test
  before_script:
    - pip install -r requirements.txt
  script:
    - coverage run --omit="*/venv/*,config/*,static/*,staticfiles/*,adminlteui/*" manage.py test apps --settings config.cicd_settings
    - COVERAGE_PERCENTAGE=$(coverage report --skip-covered | awk '/TOTAL/ {print $NF}' | tr -d '%')
    - if [ "$COVERAGE_PERCENTAGE" -lt 75 ]; then
        echo "A cobertura de código é menor do que o mínimo exigido (75%)";
        exit 1;
      fi
    - coverage report -m
    - coverage xml -i

SonarScanner:
  image: addianto/sonar-scanner-cli:latest
  stage: sonarqube
  dependencies:
    - UnitTest
  script:
    - sonar-scanner
      -Dsonar.host.url=http://192.168.0.78:9000
      -Dsonar.projectKey=template-django-admin
      -Dsonar.sources=apps
      -Dsonar.token=sqp_b683f3d1bef47464faa5f55f6b5d2b598492e478
      -Dsonar.python.coverage.reportPaths=coverage.xml
      -Dsonar.exclusions=apps/session/*,apps/core/*,apps/core/api/*,apps/django_sso_app/*
  only:
   - master
