stages:
  - test

UnitTest:
  image: python:3.8.10
  stage: test
  services:
    - postgres:12.2-alpine
  variables:
    POSTGRES_DB: tests
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
  before_script:
    - export DATABASE_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB
    - pip install -r requirements.txt
  script:
    - coverage run --omit="*/venv/*,config/*,static/*,staticfiles/*,adminlteui/*" manage.py test apps --settings config.cicd_settings
    - COVERAGE_PERCENTAGE=$(coverage report --skip-covered | awk '/TOTAL/ {print $NF}' | tr -d '%')
    - if [ "$COVERAGE_PERCENTAGE" -lt 75 ]; then
        echo "A cobertura de código é menor do que o mínimo exigido (75%)";
        exit 1;
      fi
    - coverage report -m
    - coverage xml -i
    - coverage-badge -o http://gitlab.defensoria.ce.def.br/dev-dpge/template-django-admin/badges/master/coverage.svg