CHOICES_SEXO_USER_NAO_INFORMADO = 0
CHOICES_SEXO_USER_MASCULINO = 1
CHOICES_SEXO_USER_FEMININO = 2

CHOICES_SEXO_USER = (
    (CHOICES_SEXO_USER_NAO_INFORMADO, 'Não informado'),
    (CHOICES_SEXO_USER_MASCULINO, 'Masculino'),
    (CHOICES_SEXO_USER_FEMININO, 'Feminino'),
)
