# Generated by Django 2.2.2 on 2022-06-06 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sessions.Session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=300, null=True)),
                ('ip', models.CharField(blank=True, max_length=20, null=True)),
                ('navegador', models.CharField(blank=True, max_length=300, null=True)),
                ('url', models.CharField(blank=True, max_length=300, null=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True, null=True)),
                ('metodo', models.CharField(blank=True, max_length=10, null=True)),
                ('parametros', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logrequests_usersession', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
