# Generated by Django 2.2.2 on 2022-08-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_auto_20220615_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='logrequests',
            name='ip_publico',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
