# Generated by Django 2.2.2 on 2022-12-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_auto_20221101_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='logrequests',
            name='tempo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
