# Generated by Django 3.2.7 on 2023-10-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0005_logrequests_tempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logrequests',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userpage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
