# Generated by Django 3.2.7 on 2023-10-05 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('session', '0007_alter_usersession_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='sessions.session'),
        ),
    ]
