# Generated by Django 3.2.7 on 2023-10-20 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('session', '0009_auto_20231005_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logrequests',
            name='tempo',
        ),
        migrations.AlterField(
            model_name='logrequests',
            name='ip',
            field=models.CharField(blank=True, default='Não obtido', max_length=20),
        ),
        migrations.AlterField(
            model_name='logrequests',
            name='ip_publico',
            field=models.CharField(blank=True, default='Não obtido', max_length=20),
        ),
        migrations.AlterField(
            model_name='logrequests',
            name='metodo',
            field=models.CharField(blank=True, default='Não obtido', max_length=10),
        ),
        migrations.AlterField(
            model_name='logrequests',
            name='navegador',
            field=models.CharField(blank=True, default='Não obtido', max_length=300),
        ),
        migrations.AlterField(
            model_name='logrequests',
            name='parametros',
            field=models.TextField(blank=True, default='Não obtido'),
        ),
        migrations.AlterField(
            model_name='logrequests',
            name='response',
            field=models.TextField(blank=True, default='Não obtido'),
        ),
        migrations.AlterField(
            model_name='logrequests',
            name='session_key',
            field=models.CharField(blank=True, default='Não obtido', max_length=300),
        ),
        migrations.AlterField(
            model_name='logrequests',
            name='url',
            field=models.CharField(blank=True, default='Não obtido', max_length=300),
        ),
        migrations.AlterField(
            model_name='logrequests',
            name='url_atual',
            field=models.CharField(blank=True, default='Não obtido', max_length=500),
        ),
        migrations.AlterField(
            model_name='logrequests',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='logrequests_usersession', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
