# Generated by Django 3.2.7 on 2023-10-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_trocasenhausuario_userpreferencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fusionauth_user_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='FusionAuth user ID'),
        ),
        migrations.AlterField(
            model_name='userpreferencias',
            name='preferencia',
            field=models.IntegerField(choices=[(1, 'Habilitar menu compacto')], verbose_name='Preferência'),
        ),
    ]
