# Generated by Django 3.2.7 on 2023-10-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20231019_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True, verbose_name='CPF'),
        ),
    ]
