# Generated by Django 3.2.7 on 2023-11-10 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0002_escolaridades_estadoscivis_municipios_nacionalidades'),
        ('users', '0005_alter_papeis_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bairro',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='user',
            name='cep',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='user',
            name='complemento',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='user',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_alternativo',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email alternativo'),
        ),
        migrations.AddField(
            model_name='user',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='user',
            name='escolaridade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_escolaridade', to='contrib.escolaridades'),
        ),
        migrations.AddField(
            model_name='user',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_usuarioestado', to='contrib.estados'),
        ),
        migrations.AddField(
            model_name='user',
            name='estado_civil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_estado_civil', to='contrib.estadoscivis'),
        ),
        migrations.AddField(
            model_name='user',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='user_foto', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='user',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_municipios', to='contrib.municipios'),
        ),
        migrations.AddField(
            model_name='user',
            name='nacionalidade',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_nacionalidade', to='contrib.nacionalidades'),
        ),
        migrations.AddField(
            model_name='user',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome da Mãe'),
        ),
        migrations.AddField(
            model_name='user',
            name='numero',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='user',
            name='rg',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='user',
            name='telefone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Telefone'),
        ),
    ]
