# Generated by Django 3.2.7 on 2023-11-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20231116_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='credenciaisusuario',
            name='usuario',
            field=models.CharField(max_length=128, null=True, verbose_name='password'),
        ),
    ]
