# Generated by Django 3.2.7 on 2023-11-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lembrete', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lembretes',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='lembretes',
            name='url_solicitada',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='URL'),
        ),
    ]
