# pastas_bloqueadas = {
#         'atividade-anexo':['view_atividadeanexos','view_formularioanexos'],
#         'videos-cotin':['view_cadastrovideos'],
#         'projeto-anexo':['view_projetoanexos'],
#         'processos':['view_documentosprocessos','view_documentosprocessosmultiplos','view_documentostipos'],
#         'anotacoes_estagiarios':['view_anotacoesestagiariosprocessos'],
#         'central-atualizacao-anexo':['all'],
#         'banco-peticoes':['view_arquivoclasse'],
#         'mediacao':['view_acolhimentosdocumentos'],
#         'psicossocial_nudem':['view_instrumentalnudemdocumentos'],
#         'atividades_extrajudiciais':['view_atividadesextrajudiciais'],
#         'atividades_supervisao':['view_atividadessupervisao'],
#         'anotacoes_acolhido':['view_acolhidosatividades'],
#         'reg_civil_anexos_instituicao':['cras.view_atendimentoscras'],
#         'reg_civil_anexos_defensoria':['cras.view_atendimentoscras'],
#         'reg_civil_anexos_lavratura':['cras.view_atendimentoscras'],
#         'anotacoes_cras':['view_atividadescras'],
#         'assessor_anexo':['view_atividadeassessorcras','AtividadeAssessorProcessos','view_atividadeassessoracolhidos'],
#         'instituicao':['view_documentosinstituicao'],
#         'nucleo-estagio-anexo':['view_atividade'],
#         'fase':['view_documentosprocessos','view_documentosprocessosmultiplos','view_documentostipos'],
#         'lembretes':['all'],
#         'cjr_casos_documentos':['all'],
#         'cjr_circulos_documentos':['all'],
#         'ies_providencia_solicitacao':['view_atendimentos']
# }


pastas_bloqueadas = {
        'atividade-anexo':['all'],
        'videos-cotin':['all'],
        'projeto-anexo':['all'],
        'processos':['all'],
        'anotacoes_estagiarios':['all'],
        'central-atualizacao-anexo':['all'],
        'banco-peticoes':['all'],
        'mediacao':['all'],
        'psicossocial_nudem':['all'],
        'atividades_extrajudiciais':['all'],
        'atividades_supervisao':['all'],
        'anotacoes_acolhido':['all'],
        'reg_civil_anexos_instituicao':['all'],
        'reg_civil_anexos_defensoria':['all'],
        'reg_civil_anexos_lavratura':['all'],
        'anotacoes_cras':['all'],
        'assessor_anexo':['all'],
        'instituicao':['all'],
        'nucleo-estagio-anexo':['all'],
        'fase':['all'],
        'lembretes':['all'],
        'cjr_casos_documentos':['all'],
        'cjr_circulos_documentos':['all'],
        'ies_providencia_solicitacao':['all'],
        'user_foto':['all'],
        'compact_file':['all'],
        'ies_documentos':['all'],
        'anotacoes_ies':['all'],
        'ies_providencia_solicitacao':['all'],
        'ies_modelos':['all'],
        'estagio/isencao':['all'],
        'estagio/condicao_especial':['all'],
        'estagio/portador_deficicencia':['all'],
}

arr_media_year_month = [
'reg_civil_anexos_instituicao',
'reg_civil_anexos_defensoria',
'reg_civil_anexos_lavratura'
                        ]