
PRIORIDADE_BAIXA = 1
PRIORIDADE_MEDIA = 2
PRIORIDADE_ALTA = 3

CHOICE_PRIORIDADE = (
    (PRIORIDADE_BAIXA, 'Baixa'),
    (PRIORIDADE_MEDIA, 'Media'),
    (PRIORIDADE_ALTA, 'Alta')
)

STATUS_PENDENTE = 1
STATUS_VISUALIZADO = 2
STATUS_CANCELADO = 3
STATUS_FINALIZADO = 4

CHOICES_STATUS = (
    (STATUS_PENDENTE, 'Pendente'),
    (STATUS_VISUALIZADO, 'Visualizado'),
    (STATUS_CANCELADO, 'Cancelado'),
    (STATUS_FINALIZADO, 'Finalizado')
)