# Generated by Django 3.2.7 on 2023-12-04 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certidao_localizacao', '0003_auto_20231204_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certidao',
            name='assinatura',
        ),
    ]
