# Generated by Django 3.2.7 on 2023-12-04 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0003_assinaturadocumento'),
        ('certidao_localizacao', '0004_remove_certidao_assinatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='certidao',
            name='assinatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contrib.assinaturadocumento', verbose_name='Assinatura Documento'),
        ),
    ]
